apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cluster-autoscaler
  prune: true
  validation: client
  patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: "cluster-autoscaler"
      namespace: "flux-system"
    patch: |-
      - op: replace
        path: "/spec/values/rbac/serviceAccount/annotations/eks.amazonaws.com~1role-arn"
        value: ${ROLENAME}
